language: java

matrix:
  include:
    - env: TARGET_AP_SERVER=tomcat90
      jdk: openjdk16
    - env: TARGET_AP_SERVER=tomcat90
      jdk: openjdk15
    - env: TARGET_AP_SERVER=tomcat90
      jdk: openjdk11
    - env:
      - TARGET_AP_SERVER=tomcat90
      - NEED_DEPLOY=true
      jdk: openjdk8
    - env: TARGET_AP_SERVER=tomcat85
      jdk: openjdk8
    - env: TARGET_AP_SERVER=tomcat70
      jdk: openjdk8
    - env: TARGET_AP_SERVER=tomee80
      jdk: openjdk8
    - env: TARGET_AP_SERVER=tomee71
      jdk: openjdk8
    - env: TARGET_AP_SERVER=wildfly20
      jdk: openjdk8
    - env: TARGET_AP_SERVER=wildfly13
      jdk: openjdk8
    - env: TARGET_AP_SERVER=liberty-ee8
      jdk: openjdk8
    - env: TARGET_AP_SERVER=liberty-ee7
      jdk: openjdk8
    - env: TARGET_AP_SERVER=jetty
      jdk: openjdk8
    - env: TARGET_AP_SERVER=glassfish5
      jdk: openjdk8
    - env: TARGET_AP_SERVER=glassfish4
      jdk: openjdk8
    - env: TARGET_AP_SERVER=resin
      jdk: openjdk8
  allow_failures:
    # Fail integration test because cannot unpack product zip file of application server
    - env: TARGET_AP_SERVER=wildfly20
      jdk: openjdk8
    - env: TARGET_AP_SERVER=wildfly13
      jdk: openjdk8

cache:
  directories:
    - "$HOME/.m2"

install: true

script:
  - ./mvnw -U clean verify -P ${TARGET_AP_SERVER}
